// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.25.1
// source: go-server/proto/message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型枚举
type MessageType int32

const (
	MessageType_UNKNOWN    MessageType = 0
	MessageType_HEARTBEAT  MessageType = 1 // 心跳包
	MessageType_AUTH       MessageType = 2 // 认证消息
	MessageType_CHAT       MessageType = 3 // 聊天消息
	MessageType_SYSTEM     MessageType = 4 // 系统消息
	MessageType_STUDY_ROOM MessageType = 5 // 自习室消息
	MessageType_FRIEND     MessageType = 6 // 好友消息
	MessageType_PROFILE    MessageType = 7 // 个人信息消息
	MessageType_ERROR      MessageType = 8 // 错误消息
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEARTBEAT",
		2: "AUTH",
		3: "CHAT",
		4: "SYSTEM",
		5: "STUDY_ROOM",
		6: "FRIEND",
		7: "PROFILE",
		8: "ERROR",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":    0,
		"HEARTBEAT":  1,
		"AUTH":       2,
		"CHAT":       3,
		"SYSTEM":     4,
		"STUDY_ROOM": 5,
		"FRIEND":     6,
		"PROFILE":    7,
		"ERROR":      8,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_go_server_proto_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_go_server_proto_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_go_server_proto_message_proto_rawDescGZIP(), []int{0}
}

type StudyRoomMessage_Operation int32

const (
	StudyRoomMessage_CREATE     StudyRoomMessage_Operation = 0 // 创建自习室
	StudyRoomMessage_JOIN       StudyRoomMessage_Operation = 1 // 加入自习室
	StudyRoomMessage_LEAVE      StudyRoomMessage_Operation = 2 // 离开自习室
	StudyRoomMessage_DESTROY    StudyRoomMessage_Operation = 3 // 销毁自习室
	StudyRoomMessage_GET_DETAIL StudyRoomMessage_Operation = 4 // 获取详情
)

// Enum value maps for StudyRoomMessage_Operation.
var (
	StudyRoomMessage_Operation_name = map[int32]string{
		0: "CREATE",
		1: "JOIN",
		2: "LEAVE",
		3: "DESTROY",
		4: "GET_DETAIL",
	}
	StudyRoomMessage_Operation_value = map[string]int32{
		"CREATE":     0,
		"JOIN":       1,
		"LEAVE":      2,
		"DESTROY":    3,
		"GET_DETAIL": 4,
	}
)

func (x StudyRoomMessage_Operation) Enum() *StudyRoomMessage_Operation {
	p := new(StudyRoomMessage_Operation)
	*p = x
	return p
}

func (x StudyRoomMessage_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StudyRoomMessage_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_go_server_proto_message_proto_enumTypes[1].Descriptor()
}

func (StudyRoomMessage_Operation) Type() protoreflect.EnumType {
	return &file_go_server_proto_message_proto_enumTypes[1]
}

func (x StudyRoomMessage_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StudyRoomMessage_Operation.Descriptor instead.
func (StudyRoomMessage_Operation) EnumDescriptor() ([]byte, []int) {
	return file_go_server_proto_message_proto_rawDescGZIP(), []int{5, 0}
}

type FriendMessage_Operation int32

const (
	FriendMessage_SEND_REQUEST       FriendMessage_Operation = 0 // 发送好友请求
	FriendMessage_HANDLE_REQUEST     FriendMessage_Operation = 1 // 处理好友请求
	FriendMessage_GET_LIST           FriendMessage_Operation = 2 // 获取好友列表
	FriendMessage_DELETE             FriendMessage_Operation = 3 // 删除好友
	FriendMessage_CREATE_CONTRACT    FriendMessage_Operation = 4 // 创建好友契约
	FriendMessage_TERMINATE_CONTRACT FriendMessage_Operation = 5 // 终止好友契约
	FriendMessage_GET_CONTRACTS      FriendMessage_Operation = 6 // 获取契约列表
)

// Enum value maps for FriendMessage_Operation.
var (
	FriendMessage_Operation_name = map[int32]string{
		0: "SEND_REQUEST",
		1: "HANDLE_REQUEST",
		2: "GET_LIST",
		3: "DELETE",
		4: "CREATE_CONTRACT",
		5: "TERMINATE_CONTRACT",
		6: "GET_CONTRACTS",
	}
	FriendMessage_Operation_value = map[string]int32{
		"SEND_REQUEST":       0,
		"HANDLE_REQUEST":     1,
		"GET_LIST":           2,
		"DELETE":             3,
		"CREATE_CONTRACT":    4,
		"TERMINATE_CONTRACT": 5,
		"GET_CONTRACTS":      6,
	}
)

func (x FriendMessage_Operation) Enum() *FriendMessage_Operation {
	p := new(FriendMessage_Operation)
	*p = x
	return p
}

func (x FriendMessage_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FriendMessage_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_go_server_proto_message_proto_enumTypes[2].Descriptor()
}

func (FriendMessage_Operation) Type() protoreflect.EnumType {
	return &file_go_server_proto_message_proto_enumTypes[2]
}

func (x FriendMessage_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FriendMessage_Operation.Descriptor instead.
func (FriendMessage_Operation) EnumDescriptor() ([]byte, []int) {
	return file_go_server_proto_message_proto_rawDescGZIP(), []int{6, 0}
}

type ProfileMessage_Operation int32

const (
	ProfileMessage_UPDATE ProfileMessage_Operation = 0 // 更新个人信息
	ProfileMessage_GET    ProfileMessage_Operation = 1 // 获取个人信息
)

// Enum value maps for ProfileMessage_Operation.
var (
	ProfileMessage_Operation_name = map[int32]string{
		0: "UPDATE",
		1: "GET",
	}
	ProfileMessage_Operation_value = map[string]int32{
		"UPDATE": 0,
		"GET":    1,
	}
)

func (x ProfileMessage_Operation) Enum() *ProfileMessage_Operation {
	p := new(ProfileMessage_Operation)
	*p = x
	return p
}

func (x ProfileMessage_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProfileMessage_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_go_server_proto_message_proto_enumTypes[3].Descriptor()
}

func (ProfileMessage_Operation) Type() protoreflect.EnumType {
	return &file_go_server_proto_message_proto_enumTypes[3]
}

func (x ProfileMessage_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProfileMessage_Operation.Descriptor instead.
func (ProfileMessage_Operation) EnumDescriptor() ([]byte, []int) {
	return file_go_server_proto_message_proto_rawDescGZIP(), []int{7, 0}
}

// 基础消息结构
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=proto.MessageType" json:"type,omitempty"`    // 消息类型
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // 时间戳
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                      // 加密后的消息内容
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_go_server_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_go_server_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_go_server_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// 心跳包消息
type HeartbeatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMessage) Reset() {
	*x = HeartbeatMessage{}
	mi := &file_go_server_proto_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMessage) ProtoMessage() {}

func (x *HeartbeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_go_server_proto_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMessage.ProtoReflect.Descriptor instead.
func (*HeartbeatMessage) Descriptor() ([]byte, []int) {
	return file_go_server_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 认证消息
type AuthMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                       // 认证令牌
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 设备标识
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthMessage) Reset() {
	*x = AuthMessage{}
	mi := &file_go_server_proto_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMessage) ProtoMessage() {}

func (x *AuthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_go_server_proto_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMessage.ProtoReflect.Descriptor instead.
func (*AuthMessage) Descriptor() ([]byte, []int) {
	return file_go_server_proto_message_proto_rawDescGZIP(), []int{2}
}

func (x *AuthMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthMessage) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// 聊天消息
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`         // 发送者ID
	ReceiverId    int32                  `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`   // 接收者ID
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                            // 消息内容
	MessageType   string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"` // 消息类型(text/image)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_go_server_proto_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_go_server_proto_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_go_server_proto_message_proto_rawDescGZIP(), []int{3}
}

func (x *ChatMessage) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatMessage) GetReceiverId() int32 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

// 系统消息
type SystemMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // 系统消息类型
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMessage) Reset() {
	*x = SystemMessage{}
	mi := &file_go_server_proto_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage) ProtoMessage() {}

func (x *SystemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_go_server_proto_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage.ProtoReflect.Descriptor instead.
func (*SystemMessage) Descriptor() ([]byte, []int) {
	return file_go_server_proto_message_proto_rawDescGZIP(), []int{4}
}

func (x *SystemMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SystemMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 自习室消息
type StudyRoomMessage struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Operation     StudyRoomMessage_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=proto.StudyRoomMessage_Operation" json:"operation,omitempty"` // 操作类型
	RoomId        int32                      `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                               // 自习室ID
	Name          string                     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                  // 自习室名称
	MaxMembers    int32                      `protobuf:"varint,4,opt,name=max_members,json=maxMembers,proto3" json:"max_members,omitempty"`                   // 最大成员数
	IsPrivate     bool                       `protobuf:"varint,5,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`                      // 是否私有
	Duration      string                     `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`                                          // 持续时间
	ShareLink     string                     `protobuf:"bytes,7,opt,name=share_link,json=shareLink,proto3" json:"share_link,omitempty"`                       // 分享链接
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudyRoomMessage) Reset() {
	*x = StudyRoomMessage{}
	mi := &file_go_server_proto_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudyRoomMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyRoomMessage) ProtoMessage() {}

func (x *StudyRoomMessage) ProtoReflect() protoreflect.Message {
	mi := &file_go_server_proto_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyRoomMessage.ProtoReflect.Descriptor instead.
func (*StudyRoomMessage) Descriptor() ([]byte, []int) {
	return file_go_server_proto_message_proto_rawDescGZIP(), []int{5}
}

func (x *StudyRoomMessage) GetOperation() StudyRoomMessage_Operation {
	if x != nil {
		return x.Operation
	}
	return StudyRoomMessage_CREATE
}

func (x *StudyRoomMessage) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *StudyRoomMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudyRoomMessage) GetMaxMembers() int32 {
	if x != nil {
		return x.MaxMembers
	}
	return 0
}

func (x *StudyRoomMessage) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *StudyRoomMessage) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *StudyRoomMessage) GetShareLink() string {
	if x != nil {
		return x.ShareLink
	}
	return ""
}

// 好友消息
type FriendMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Operation     FriendMessage_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=proto.FriendMessage_Operation" json:"operation,omitempty"` // 操作类型
	FriendId      int32                   `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`                      // 好友ID
	Action        string                  `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`                                           // 操作动作
	ContractType  string                  `protobuf:"bytes,4,opt,name=contract_type,json=contractType,proto3" json:"contract_type,omitempty"`           // 契约类型
	ContractTerms string                  `protobuf:"bytes,5,opt,name=contract_terms,json=contractTerms,proto3" json:"contract_terms,omitempty"`        // 契约条款
	ContractId    int32                   `protobuf:"varint,6,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`                // 契约ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendMessage) Reset() {
	*x = FriendMessage{}
	mi := &file_go_server_proto_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendMessage) ProtoMessage() {}

func (x *FriendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_go_server_proto_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendMessage.ProtoReflect.Descriptor instead.
func (*FriendMessage) Descriptor() ([]byte, []int) {
	return file_go_server_proto_message_proto_rawDescGZIP(), []int{6}
}

func (x *FriendMessage) GetOperation() FriendMessage_Operation {
	if x != nil {
		return x.Operation
	}
	return FriendMessage_SEND_REQUEST
}

func (x *FriendMessage) GetFriendId() int32 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *FriendMessage) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FriendMessage) GetContractType() string {
	if x != nil {
		return x.ContractType
	}
	return ""
}

func (x *FriendMessage) GetContractTerms() string {
	if x != nil {
		return x.ContractTerms
	}
	return ""
}

func (x *FriendMessage) GetContractId() int32 {
	if x != nil {
		return x.ContractId
	}
	return 0
}

// 个人信息消息
type ProfileMessage struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Operation      ProfileMessage_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=proto.ProfileMessage_Operation" json:"operation,omitempty"` // 操作类型
	Username       string                   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                                        // 用户名
	Signature      string                   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                                      // 个性签名
	StudyDirection string                   `protobuf:"bytes,4,opt,name=study_direction,json=studyDirection,proto3" json:"study_direction,omitempty"`      // 学习方向
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProfileMessage) Reset() {
	*x = ProfileMessage{}
	mi := &file_go_server_proto_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileMessage) ProtoMessage() {}

func (x *ProfileMessage) ProtoReflect() protoreflect.Message {
	mi := &file_go_server_proto_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileMessage.ProtoReflect.Descriptor instead.
func (*ProfileMessage) Descriptor() ([]byte, []int) {
	return file_go_server_proto_message_proto_rawDescGZIP(), []int{7}
}

func (x *ProfileMessage) GetOperation() ProfileMessage_Operation {
	if x != nil {
		return x.Operation
	}
	return ProfileMessage_UPDATE
}

func (x *ProfileMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProfileMessage) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ProfileMessage) GetStudyDirection() string {
	if x != nil {
		return x.StudyDirection
	}
	return ""
}

// 错误消息
type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                           // 错误码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 错误信息
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`                        // 详细错误信息
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 请求ID，用于追踪
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_go_server_proto_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_go_server_proto_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_go_server_proto_message_proto_rawDescGZIP(), []int{8}
}

func (x *ErrorMessage) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorMessage) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ErrorMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_go_server_proto_message_proto protoreflect.FileDescriptor

var file_go_server_proto_message_proto_rawDesc = string([]byte{
	0x0a, 0x1d, 0x67, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x88, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x22, 0x30, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x22, 0x40, 0x0a, 0x0b, 0x41, 0x75, 0x74, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x64, 0x22, 0x88, 0x01, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a,
	0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x3d, 0x0a, 0x0d, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0xc6, 0x02, 0x0a, 0x10, 0x53, 0x74, 0x75, 0x64, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x3f, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x74, 0x75, 0x64, 0x79, 0x52, 0x6f, 0x6f, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x78, 0x5f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x6d, 0x61, 0x78, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x50, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x61, 0x72, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x22, 0x49, 0x0a,
	0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x52,
	0x45, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x4f, 0x49, 0x4e, 0x10, 0x01,
	0x12, 0x09, 0x0a, 0x05, 0x4c, 0x45, 0x41, 0x56, 0x45, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x44,
	0x45, 0x53, 0x54, 0x52, 0x4f, 0x59, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x47, 0x45, 0x54, 0x5f,
	0x44, 0x45, 0x54, 0x41, 0x49, 0x4c, 0x10, 0x04, 0x22, 0xfd, 0x02, 0x0a, 0x0d, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a,
	0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x74,
	0x65, 0x72, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x54, 0x65, 0x72, 0x6d, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x22, 0x8b, 0x01, 0x0a, 0x09, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x4e, 0x44,
	0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x48, 0x41,
	0x4e, 0x44, 0x4c, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x47, 0x45, 0x54, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06,
	0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x52, 0x45, 0x41,
	0x54, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52, 0x41, 0x43, 0x54, 0x10, 0x04, 0x12, 0x16, 0x0a,
	0x12, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4f, 0x4e, 0x54, 0x52,
	0x41, 0x43, 0x54, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x47, 0x45, 0x54, 0x5f, 0x43, 0x4f, 0x4e,
	0x54, 0x52, 0x41, 0x43, 0x54, 0x53, 0x10, 0x06, 0x22, 0xd4, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x6f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x74, 0x75, 0x64, 0x79, 0x5f, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73,
	0x74, 0x75, 0x64, 0x79, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x20, 0x0a,
	0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50,
	0x44, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45, 0x54, 0x10, 0x01, 0x22,
	0x73, 0x0a, 0x0c, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x2a, 0x7d, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x0d, 0x0a, 0x09, 0x48, 0x45, 0x41, 0x52, 0x54, 0x42, 0x45, 0x41, 0x54, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x41, 0x55, 0x54, 0x48, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x48, 0x41,
	0x54, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x59, 0x53, 0x54, 0x45, 0x4d, 0x10, 0x04, 0x12,
	0x0e, 0x0a, 0x0a, 0x53, 0x54, 0x55, 0x44, 0x59, 0x5f, 0x52, 0x4f, 0x4f, 0x4d, 0x10, 0x05, 0x12,
	0x0a, 0x0a, 0x06, 0x46, 0x52, 0x49, 0x45, 0x4e, 0x44, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07, 0x50,
	0x52, 0x4f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f,
	0x52, 0x10, 0x08, 0x42, 0x11, 0x5a, 0x0f, 0x67, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_go_server_proto_message_proto_rawDescOnce sync.Once
	file_go_server_proto_message_proto_rawDescData []byte
)

func file_go_server_proto_message_proto_rawDescGZIP() []byte {
	file_go_server_proto_message_proto_rawDescOnce.Do(func() {
		file_go_server_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_server_proto_message_proto_rawDesc), len(file_go_server_proto_message_proto_rawDesc)))
	})
	return file_go_server_proto_message_proto_rawDescData
}

var file_go_server_proto_message_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_go_server_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_go_server_proto_message_proto_goTypes = []any{
	(MessageType)(0),                // 0: proto.MessageType
	(StudyRoomMessage_Operation)(0), // 1: proto.StudyRoomMessage.Operation
	(FriendMessage_Operation)(0),    // 2: proto.FriendMessage.Operation
	(ProfileMessage_Operation)(0),   // 3: proto.ProfileMessage.Operation
	(*Message)(nil),                 // 4: proto.Message
	(*HeartbeatMessage)(nil),        // 5: proto.HeartbeatMessage
	(*AuthMessage)(nil),             // 6: proto.AuthMessage
	(*ChatMessage)(nil),             // 7: proto.ChatMessage
	(*SystemMessage)(nil),           // 8: proto.SystemMessage
	(*StudyRoomMessage)(nil),        // 9: proto.StudyRoomMessage
	(*FriendMessage)(nil),           // 10: proto.FriendMessage
	(*ProfileMessage)(nil),          // 11: proto.ProfileMessage
	(*ErrorMessage)(nil),            // 12: proto.ErrorMessage
}
var file_go_server_proto_message_proto_depIdxs = []int32{
	0, // 0: proto.Message.type:type_name -> proto.MessageType
	1, // 1: proto.StudyRoomMessage.operation:type_name -> proto.StudyRoomMessage.Operation
	2, // 2: proto.FriendMessage.operation:type_name -> proto.FriendMessage.Operation
	3, // 3: proto.ProfileMessage.operation:type_name -> proto.ProfileMessage.Operation
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_go_server_proto_message_proto_init() }
func file_go_server_proto_message_proto_init() {
	if File_go_server_proto_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_server_proto_message_proto_rawDesc), len(file_go_server_proto_message_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_server_proto_message_proto_goTypes,
		DependencyIndexes: file_go_server_proto_message_proto_depIdxs,
		EnumInfos:         file_go_server_proto_message_proto_enumTypes,
		MessageInfos:      file_go_server_proto_message_proto_msgTypes,
	}.Build()
	File_go_server_proto_message_proto = out.File
	file_go_server_proto_message_proto_goTypes = nil
	file_go_server_proto_message_proto_depIdxs = nil
}
