// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.1
// source: message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型枚举
type MessageType int32

const (
	MessageType_UNKNOWN    MessageType = 0
	MessageType_HEARTBEAT  MessageType = 1 // 心跳包
	MessageType_AUTH       MessageType = 2 // 认证消息
	MessageType_CHAT       MessageType = 3 // 聊天消息
	MessageType_SYSTEM     MessageType = 4 // 系统消息
	MessageType_STUDY_ROOM MessageType = 5 // 自习室消息
	MessageType_FRIEND     MessageType = 6 // 好友消息
	MessageType_PROFILE    MessageType = 7 // 个人信息消息
	MessageType_ERROR      MessageType = 8 // 错误消息
	MessageType_REGISTER   MessageType = 9 // 注册消息
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNKNOWN",
		1: "HEARTBEAT",
		2: "AUTH",
		3: "CHAT",
		4: "SYSTEM",
		5: "STUDY_ROOM",
		6: "FRIEND",
		7: "PROFILE",
		8: "ERROR",
		9: "REGISTER",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":    0,
		"HEARTBEAT":  1,
		"AUTH":       2,
		"CHAT":       3,
		"SYSTEM":     4,
		"STUDY_ROOM": 5,
		"FRIEND":     6,
		"PROFILE":    7,
		"ERROR":      8,
		"REGISTER":   9,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

type StudyRoomMessage_Operation int32

const (
	StudyRoomMessage_CREATE     StudyRoomMessage_Operation = 0 // 创建自习室
	StudyRoomMessage_JOIN       StudyRoomMessage_Operation = 1 // 加入自习室
	StudyRoomMessage_LEAVE      StudyRoomMessage_Operation = 2 // 离开自习室
	StudyRoomMessage_DESTROY    StudyRoomMessage_Operation = 3 // 销毁自习室
	StudyRoomMessage_GET_DETAIL StudyRoomMessage_Operation = 4 // 获取详情
)

// Enum value maps for StudyRoomMessage_Operation.
var (
	StudyRoomMessage_Operation_name = map[int32]string{
		0: "CREATE",
		1: "JOIN",
		2: "LEAVE",
		3: "DESTROY",
		4: "GET_DETAIL",
	}
	StudyRoomMessage_Operation_value = map[string]int32{
		"CREATE":     0,
		"JOIN":       1,
		"LEAVE":      2,
		"DESTROY":    3,
		"GET_DETAIL": 4,
	}
)

func (x StudyRoomMessage_Operation) Enum() *StudyRoomMessage_Operation {
	p := new(StudyRoomMessage_Operation)
	*p = x
	return p
}

func (x StudyRoomMessage_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StudyRoomMessage_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[1].Descriptor()
}

func (StudyRoomMessage_Operation) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[1]
}

func (x StudyRoomMessage_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StudyRoomMessage_Operation.Descriptor instead.
func (StudyRoomMessage_Operation) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6, 0}
}

type FriendMessage_Operation int32

const (
	FriendMessage_SEND_REQUEST       FriendMessage_Operation = 0 // 发送好友请求
	FriendMessage_HANDLE_REQUEST     FriendMessage_Operation = 1 // 处理好友请求
	FriendMessage_GET_LIST           FriendMessage_Operation = 2 // 获取好友列表
	FriendMessage_DELETE             FriendMessage_Operation = 3 // 删除好友
	FriendMessage_CREATE_CONTRACT    FriendMessage_Operation = 4 // 创建好友契约
	FriendMessage_TERMINATE_CONTRACT FriendMessage_Operation = 5 // 终止好友契约
	FriendMessage_GET_CONTRACTS      FriendMessage_Operation = 6 // 获取契约列表
)

// Enum value maps for FriendMessage_Operation.
var (
	FriendMessage_Operation_name = map[int32]string{
		0: "SEND_REQUEST",
		1: "HANDLE_REQUEST",
		2: "GET_LIST",
		3: "DELETE",
		4: "CREATE_CONTRACT",
		5: "TERMINATE_CONTRACT",
		6: "GET_CONTRACTS",
	}
	FriendMessage_Operation_value = map[string]int32{
		"SEND_REQUEST":       0,
		"HANDLE_REQUEST":     1,
		"GET_LIST":           2,
		"DELETE":             3,
		"CREATE_CONTRACT":    4,
		"TERMINATE_CONTRACT": 5,
		"GET_CONTRACTS":      6,
	}
)

func (x FriendMessage_Operation) Enum() *FriendMessage_Operation {
	p := new(FriendMessage_Operation)
	*p = x
	return p
}

func (x FriendMessage_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FriendMessage_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[2].Descriptor()
}

func (FriendMessage_Operation) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[2]
}

func (x FriendMessage_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FriendMessage_Operation.Descriptor instead.
func (FriendMessage_Operation) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7, 0}
}

type ProfileMessage_Operation int32

const (
	ProfileMessage_UPDATE ProfileMessage_Operation = 0 // 更新个人信息
	ProfileMessage_GET    ProfileMessage_Operation = 1 // 获取个人信息
)

// Enum value maps for ProfileMessage_Operation.
var (
	ProfileMessage_Operation_name = map[int32]string{
		0: "UPDATE",
		1: "GET",
	}
	ProfileMessage_Operation_value = map[string]int32{
		"UPDATE": 0,
		"GET":    1,
	}
)

func (x ProfileMessage_Operation) Enum() *ProfileMessage_Operation {
	p := new(ProfileMessage_Operation)
	*p = x
	return p
}

func (x ProfileMessage_Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProfileMessage_Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_message_proto_enumTypes[3].Descriptor()
}

func (ProfileMessage_Operation) Type() protoreflect.EnumType {
	return &file_message_proto_enumTypes[3]
}

func (x ProfileMessage_Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProfileMessage_Operation.Descriptor instead.
func (ProfileMessage_Operation) EnumDescriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8, 0}
}

// 基础消息结构
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=proto.MessageType" json:"type,omitempty"`    // 消息类型
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                 // 时间戳
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                      // 加密后的消息内容
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// 心跳包消息
type HeartbeatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatMessage) Reset() {
	*x = HeartbeatMessage{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatMessage) ProtoMessage() {}

func (x *HeartbeatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatMessage.ProtoReflect.Descriptor instead.
func (*HeartbeatMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 认证消息
type AuthMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                       // 认证令牌
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 设备标识
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthMessage) Reset() {
	*x = AuthMessage{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthMessage) ProtoMessage() {}

func (x *AuthMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthMessage.ProtoReflect.Descriptor instead.
func (*AuthMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *AuthMessage) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthMessage) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AuthMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 注册消息
type RegisterMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"` // 用户名
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // 密码
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`       // 邮箱
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterMessage) Reset() {
	*x = RegisterMessage{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterMessage) ProtoMessage() {}

func (x *RegisterMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterMessage.ProtoReflect.Descriptor instead.
func (*RegisterMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterMessage) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// 聊天消息
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int32                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`         // 发送者ID
	ReceiverId    int32                  `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`   // 接收者ID
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                            // 消息内容
	MessageType   string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"` // 消息类型(text/image)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *ChatMessage) GetSenderId() int32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatMessage) GetReceiverId() int32 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

// 系统消息
type SystemMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // 系统消息类型
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMessage) Reset() {
	*x = SystemMessage{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMessage) ProtoMessage() {}

func (x *SystemMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMessage.ProtoReflect.Descriptor instead.
func (*SystemMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *SystemMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SystemMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 自习室消息
type StudyRoomMessage struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Operation     StudyRoomMessage_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=proto.StudyRoomMessage_Operation" json:"operation,omitempty"` // 操作类型
	RoomId        int32                      `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                               // 自习室ID
	Name          string                     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                                  // 自习室名称
	MaxMembers    int32                      `protobuf:"varint,4,opt,name=max_members,json=maxMembers,proto3" json:"max_members,omitempty"`                   // 最大成员数
	IsPrivate     bool                       `protobuf:"varint,5,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`                      // 是否私有
	Duration      string                     `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`                                          // 持续时间
	ShareLink     string                     `protobuf:"bytes,7,opt,name=share_link,json=shareLink,proto3" json:"share_link,omitempty"`                       // 分享链接
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudyRoomMessage) Reset() {
	*x = StudyRoomMessage{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudyRoomMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyRoomMessage) ProtoMessage() {}

func (x *StudyRoomMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyRoomMessage.ProtoReflect.Descriptor instead.
func (*StudyRoomMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *StudyRoomMessage) GetOperation() StudyRoomMessage_Operation {
	if x != nil {
		return x.Operation
	}
	return StudyRoomMessage_CREATE
}

func (x *StudyRoomMessage) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *StudyRoomMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudyRoomMessage) GetMaxMembers() int32 {
	if x != nil {
		return x.MaxMembers
	}
	return 0
}

func (x *StudyRoomMessage) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *StudyRoomMessage) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *StudyRoomMessage) GetShareLink() string {
	if x != nil {
		return x.ShareLink
	}
	return ""
}

// 好友消息
type FriendMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Operation     FriendMessage_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=proto.FriendMessage_Operation" json:"operation,omitempty"` // 操作类型
	FriendId      int32                   `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`                      // 好友ID
	Action        string                  `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`                                           // 操作动作
	ContractType  string                  `protobuf:"bytes,4,opt,name=contract_type,json=contractType,proto3" json:"contract_type,omitempty"`           // 契约类型
	ContractTerms string                  `protobuf:"bytes,5,opt,name=contract_terms,json=contractTerms,proto3" json:"contract_terms,omitempty"`        // 契约条款
	ContractId    int32                   `protobuf:"varint,6,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`                // 契约ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendMessage) Reset() {
	*x = FriendMessage{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendMessage) ProtoMessage() {}

func (x *FriendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendMessage.ProtoReflect.Descriptor instead.
func (*FriendMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *FriendMessage) GetOperation() FriendMessage_Operation {
	if x != nil {
		return x.Operation
	}
	return FriendMessage_SEND_REQUEST
}

func (x *FriendMessage) GetFriendId() int32 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *FriendMessage) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FriendMessage) GetContractType() string {
	if x != nil {
		return x.ContractType
	}
	return ""
}

func (x *FriendMessage) GetContractTerms() string {
	if x != nil {
		return x.ContractTerms
	}
	return ""
}

func (x *FriendMessage) GetContractId() int32 {
	if x != nil {
		return x.ContractId
	}
	return 0
}

// 个人信息消息
type ProfileMessage struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Operation      ProfileMessage_Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=proto.ProfileMessage_Operation" json:"operation,omitempty"` // 操作类型
	Username       string                   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                                        // 用户名
	Signature      string                   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                                      // 个性签名
	StudyDirection string                   `protobuf:"bytes,4,opt,name=study_direction,json=studyDirection,proto3" json:"study_direction,omitempty"`      // 学习方向
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProfileMessage) Reset() {
	*x = ProfileMessage{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileMessage) ProtoMessage() {}

func (x *ProfileMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileMessage.ProtoReflect.Descriptor instead.
func (*ProfileMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *ProfileMessage) GetOperation() ProfileMessage_Operation {
	if x != nil {
		return x.Operation
	}
	return ProfileMessage_UPDATE
}

func (x *ProfileMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ProfileMessage) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ProfileMessage) GetStudyDirection() string {
	if x != nil {
		return x.StudyDirection
	}
	return ""
}

// 错误消息
type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                           // 错误码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                      // 错误信息
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`                        // 详细错误信息
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 请求ID，用于追踪
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

func (x *ErrorMessage) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorMessage) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ErrorMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\x05proto\"\x88\x01\n" +
	"\aMessage\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.proto.MessageTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"0\n" +
	"\x10HeartbeatMessage\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"\x8e\x01\n" +
	"\vAuthMessage\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"_\n" +
	"\x0fRegisterMessage\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\x88\x01\n" +
	"\vChatMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x05R\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\x05R\n" +
	"receiverId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\"=\n" +
	"\rSystemMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xc6\x02\n" +
	"\x10StudyRoomMessage\x12?\n" +
	"\toperation\x18\x01 \x01(\x0e2!.proto.StudyRoomMessage.OperationR\toperation\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x05R\x06roomId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vmax_members\x18\x04 \x01(\x05R\n" +
	"maxMembers\x12\x1d\n" +
	"\n" +
	"is_private\x18\x05 \x01(\bR\tisPrivate\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\tR\bduration\x12\x1d\n" +
	"\n" +
	"share_link\x18\a \x01(\tR\tshareLink\"I\n" +
	"\tOperation\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\b\n" +
	"\x04JOIN\x10\x01\x12\t\n" +
	"\x05LEAVE\x10\x02\x12\v\n" +
	"\aDESTROY\x10\x03\x12\x0e\n" +
	"\n" +
	"GET_DETAIL\x10\x04\"\xfd\x02\n" +
	"\rFriendMessage\x12<\n" +
	"\toperation\x18\x01 \x01(\x0e2\x1e.proto.FriendMessage.OperationR\toperation\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x05R\bfriendId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12#\n" +
	"\rcontract_type\x18\x04 \x01(\tR\fcontractType\x12%\n" +
	"\x0econtract_terms\x18\x05 \x01(\tR\rcontractTerms\x12\x1f\n" +
	"\vcontract_id\x18\x06 \x01(\x05R\n" +
	"contractId\"\x8b\x01\n" +
	"\tOperation\x12\x10\n" +
	"\fSEND_REQUEST\x10\x00\x12\x12\n" +
	"\x0eHANDLE_REQUEST\x10\x01\x12\f\n" +
	"\bGET_LIST\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03\x12\x13\n" +
	"\x0fCREATE_CONTRACT\x10\x04\x12\x16\n" +
	"\x12TERMINATE_CONTRACT\x10\x05\x12\x11\n" +
	"\rGET_CONTRACTS\x10\x06\"\xd4\x01\n" +
	"\x0eProfileMessage\x12=\n" +
	"\toperation\x18\x01 \x01(\x0e2\x1f.proto.ProfileMessage.OperationR\toperation\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12'\n" +
	"\x0fstudy_direction\x18\x04 \x01(\tR\x0estudyDirection\" \n" +
	"\tOperation\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x00\x12\a\n" +
	"\x03GET\x10\x01\"s\n" +
	"\fErrorMessage\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId*\x8b\x01\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tHEARTBEAT\x10\x01\x12\b\n" +
	"\x04AUTH\x10\x02\x12\b\n" +
	"\x04CHAT\x10\x03\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x04\x12\x0e\n" +
	"\n" +
	"STUDY_ROOM\x10\x05\x12\n" +
	"\n" +
	"\x06FRIEND\x10\x06\x12\v\n" +
	"\aPROFILE\x10\a\x12\t\n" +
	"\x05ERROR\x10\b\x12\f\n" +
	"\bREGISTER\x10\tB\x11Z\x0fgo-server/protob\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_message_proto_goTypes = []any{
	(MessageType)(0),                // 0: proto.MessageType
	(StudyRoomMessage_Operation)(0), // 1: proto.StudyRoomMessage.Operation
	(FriendMessage_Operation)(0),    // 2: proto.FriendMessage.Operation
	(ProfileMessage_Operation)(0),   // 3: proto.ProfileMessage.Operation
	(*Message)(nil),                 // 4: proto.Message
	(*HeartbeatMessage)(nil),        // 5: proto.HeartbeatMessage
	(*AuthMessage)(nil),             // 6: proto.AuthMessage
	(*RegisterMessage)(nil),         // 7: proto.RegisterMessage
	(*ChatMessage)(nil),             // 8: proto.ChatMessage
	(*SystemMessage)(nil),           // 9: proto.SystemMessage
	(*StudyRoomMessage)(nil),        // 10: proto.StudyRoomMessage
	(*FriendMessage)(nil),           // 11: proto.FriendMessage
	(*ProfileMessage)(nil),          // 12: proto.ProfileMessage
	(*ErrorMessage)(nil),            // 13: proto.ErrorMessage
}
var file_message_proto_depIdxs = []int32{
	0, // 0: proto.Message.type:type_name -> proto.MessageType
	1, // 1: proto.StudyRoomMessage.operation:type_name -> proto.StudyRoomMessage.Operation
	2, // 2: proto.FriendMessage.operation:type_name -> proto.FriendMessage.Operation
	3, // 3: proto.ProfileMessage.operation:type_name -> proto.ProfileMessage.Operation
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		EnumInfos:         file_message_proto_enumTypes,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
